from collections.abc import Callable
from typing import Any

type LayoutRepaintFact = tuple[object, int, bool, bool, int, int, int, int, int, int, int, int]

# Enums (nanobind enum types)
class Direction:
    Inherit: Direction
    LTR: Direction
    RTL: Direction
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class FlexDirection:
    Column: FlexDirection
    ColumnReverse: FlexDirection
    Row: FlexDirection
    RowReverse: FlexDirection
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class Justify:
    FlexStart: Justify
    Center: Justify
    FlexEnd: Justify
    SpaceBetween: Justify
    SpaceAround: Justify
    SpaceEvenly: Justify
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class Align:
    Auto: Align
    FlexStart: Align
    Center: Align
    FlexEnd: Align
    Stretch: Align
    Baseline: Align
    SpaceBetween: Align
    SpaceAround: Align
    SpaceEvenly: Align
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class PositionType:
    Static: PositionType
    Relative: PositionType
    Absolute: PositionType
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class Wrap:
    NoWrap: Wrap
    Wrap: Wrap
    WrapReverse: Wrap
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class Overflow:
    Visible: Overflow
    Hidden: Overflow
    Scroll: Overflow
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class Display:
    Flex: Display
    None_: Display
    Contents: Display
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class Edge:
    Left: Edge
    Top: Edge
    Right: Edge
    Bottom: Edge
    Start: Edge
    End: Edge
    Horizontal: Edge
    Vertical: Edge
    All: Edge
    __members__: dict[str, Edge]
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class Unit:
    Undefined: Unit
    Point: Unit
    Percent: Unit
    Auto: Unit
    MaxContent: Unit
    FitContent: Unit
    Stretch: Unit
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class MeasureMode:
    Undefined: MeasureMode
    Exactly: MeasureMode
    AtMost: MeasureMode
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class Dimension:
    Width: Dimension
    Height: Dimension
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class NodeType:
    Default: NodeType
    Text: NodeType
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class LogLevel:
    Error: LogLevel
    Warn: LogLevel
    Info: LogLevel
    Debug: LogLevel
    Verbose: LogLevel
    Fatal: LogLevel
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class ExperimentalFeature:
    WebFlexBasis: ExperimentalFeature
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class Gutter:
    Column: Gutter
    Row: Gutter
    All: Gutter
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class BoxSizing:
    BorderBox: BoxSizing
    ContentBox: BoxSizing
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class Errata:
    None_: Errata
    StretchFlexBasis: Errata
    AbsolutePositionWithoutInsetsExcludesPadding: Errata
    AbsolutePercentAgainstInnerSize: Errata
    All: Errata
    Classic: Errata
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

class EventType:
    NodeAllocation: EventType
    NodeDeallocation: EventType
    NodeLayout: EventType
    LayoutPassStart: EventType
    LayoutPassEnd: EventType
    MeasureCallbackStart: EventType
    MeasureCallbackEnd: EventType
    NodeBaselineStart: EventType
    NodeBaselineEnd: EventType
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...

# EventType constants at module level
NodeAllocation: EventType
NodeDeallocation: EventType
NodeLayout: EventType
LayoutPassStart: EventType
LayoutPassEnd: EventType
MeasureCallbackStart: EventType
MeasureCallbackEnd: EventType
NodeBaselineStart: EventType
NodeBaselineEnd: EventType

# YGValue
class YGValue:
    value: float
    unit: Unit | int
    def __init__(self, value: float, unit: Unit | int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __neg__(self) -> YGValue: ...
    def __repr__(self) -> str: ...

YGValueAuto: YGValue
YGValueUndefined: YGValue
YGValueZero: YGValue
YGValueFitContent: YGValue

def YGValuePoint(value: float) -> YGValue: ...
def YGValuePercent(value: float) -> YGValue: ...
def YGFloatIsUndefined(value: float) -> bool: ...
def round_value_to_pixel_grid(
    value: float,
    point_scale_factor: float,
    ceil: bool = False,
    floor: bool = False,
) -> float: ...

# LayoutData
class LayoutData:
    layouts: int
    measures: int
    maxMeasureCache: int
    cachedLayouts: int
    cachedMeasures: int
    measureCallbacks: int

# Config
class Config:
    def __init__(self) -> None: ...
    @property
    def use_web_defaults(self) -> bool: ...
    @use_web_defaults.setter
    def use_web_defaults(self, value: bool) -> None: ...
    @property
    def point_scale_factor(self) -> float: ...
    @point_scale_factor.setter
    def point_scale_factor(self, value: float) -> None: ...
    @property
    def errata(self) -> Errata: ...
    @errata.setter
    def errata(self, value: Errata | int) -> None: ...
    def set_experimental_feature_enabled(
        self, feature: ExperimentalFeature | int, enabled: bool
    ) -> None: ...
    def is_experimental_feature_enabled(self, feature: ExperimentalFeature | int) -> bool: ...
    def set_clone_node_callback(self, callback: Callable[..., Any] | None) -> None: ...
    def clone_node(self, node: Node, owner: Node | None = None, child_index: int = 0) -> Node: ...
    def set_logger(self, logger: Callable[..., Any] | None) -> None: ...

# Node
class Node:
    def __init__(self, config: Config | None = None) -> None: ...

    # Tree manipulation
    def insert_child(self, child: Node, index: int) -> None: ...
    def remove_child(self, child: Node) -> None: ...
    def remove_all_children(self) -> None: ...
    def set_children(self, children: list[Node]) -> None: ...
    def swap_child(self, child: Node, index: int) -> None: ...
    @property
    def child_count(self) -> int: ...
    @property
    def owner(self) -> Node | None: ...
    @property
    def parent(self) -> Node | None: ...
    def get_layout_children(self) -> list[Node]: ...

    # Lifecycle
    def free(self) -> None: ...
    def free_recursive(self) -> None: ...
    def clone(self) -> Node: ...
    def reset(self) -> None: ...
    def copy_style(self, other: Node) -> None: ...
    def set_config(self, config: Config) -> None: ...
    def get_config(self) -> Config: ...
    def _node_id(self) -> int: ...

    # Dirty state
    @property
    def is_dirty(self) -> bool: ...
    def set_dirty(self, dirty: bool) -> None: ...
    def mark_dirty(self) -> None: ...
    def mark_dirty_and_propagate(self) -> None: ...
    @property
    def has_new_layout(self) -> bool: ...
    @has_new_layout.setter
    def has_new_layout(self, value: bool) -> None: ...
    def __getitem__(self, index: int) -> Node: ...

    # Callbacks
    def set_measure_func(self, func: Callable[..., Any] | None) -> None: ...
    def has_measure_func(self) -> bool: ...
    def set_baseline_func(self, func: Callable[..., Any] | None) -> None: ...
    def has_baseline_func(self) -> bool: ...
    def set_dirtied_func(self, func: Callable[..., Any] | None) -> None: ...
    def set_context(self, context: Any) -> None: ...
    def measure(
        self,
        width: float,
        width_mode: MeasureMode | int,
        height: float,
        height_mode: MeasureMode | int,
    ) -> dict[str, float]: ...
    def baseline(self, width: float, height: float) -> float: ...

    # Style properties (read/write)
    @property
    def direction(self) -> Direction: ...
    @direction.setter
    def direction(self, value: Direction | int) -> None: ...
    @property
    def flex_direction(self) -> FlexDirection: ...
    @flex_direction.setter
    def flex_direction(self, value: FlexDirection | int) -> None: ...
    @property
    def justify_content(self) -> Justify: ...
    @justify_content.setter
    def justify_content(self, value: Justify | int) -> None: ...
    @property
    def align_content(self) -> Align: ...
    @align_content.setter
    def align_content(self, value: Align | int) -> None: ...
    @property
    def align_items(self) -> Align: ...
    @align_items.setter
    def align_items(self, value: Align | int) -> None: ...
    @property
    def align_self(self) -> Align: ...
    @align_self.setter
    def align_self(self, value: Align | int) -> None: ...
    @property
    def position_type(self) -> PositionType: ...
    @position_type.setter
    def position_type(self, value: PositionType | int) -> None: ...
    @property
    def flex_wrap(self) -> Wrap: ...
    @flex_wrap.setter
    def flex_wrap(self, value: Wrap | int) -> None: ...
    @property
    def overflow(self) -> Overflow: ...
    @overflow.setter
    def overflow(self, value: Overflow | int) -> None: ...
    @property
    def display(self) -> Display: ...
    @display.setter
    def display(self, value: Display | int) -> None: ...
    @property
    def flex(self) -> float: ...
    @flex.setter
    def flex(self, value: float) -> None: ...
    @property
    def flex_grow(self) -> float: ...
    @flex_grow.setter
    def flex_grow(self, value: float) -> None: ...
    @property
    def flex_shrink(self) -> float: ...
    @flex_shrink.setter
    def flex_shrink(self, value: float) -> None: ...
    @property
    def flex_basis(self) -> YGValue: ...
    @flex_basis.setter
    def flex_basis(self, value: YGValue | float) -> None: ...
    @property
    def width(self) -> YGValue: ...
    @width.setter
    def width(self, value: YGValue | float) -> None: ...
    @property
    def height(self) -> YGValue: ...
    @height.setter
    def height(self, value: YGValue | float) -> None: ...
    @property
    def min_width(self) -> YGValue: ...
    @min_width.setter
    def min_width(self, value: YGValue | float) -> None: ...
    @property
    def min_height(self) -> YGValue: ...
    @min_height.setter
    def min_height(self, value: YGValue | float) -> None: ...
    @property
    def max_width(self) -> YGValue: ...
    @max_width.setter
    def max_width(self, value: YGValue | float) -> None: ...
    @property
    def max_height(self) -> YGValue: ...
    @max_height.setter
    def max_height(self, value: YGValue | float) -> None: ...
    @property
    def aspect_ratio(self) -> float: ...
    @aspect_ratio.setter
    def aspect_ratio(self, value: float) -> None: ...
    @property
    def box_sizing(self) -> BoxSizing: ...
    @box_sizing.setter
    def box_sizing(self, value: BoxSizing | int) -> None: ...
    @property
    def node_type(self) -> NodeType: ...
    @node_type.setter
    def node_type(self, value: NodeType | int) -> None: ...
    @property
    def is_reference_baseline(self) -> bool: ...
    @is_reference_baseline.setter
    def is_reference_baseline(self, value: bool) -> None: ...
    @property
    def always_forms_containing_block(self) -> bool: ...
    @always_forms_containing_block.setter
    def always_forms_containing_block(self, value: bool) -> None: ...

    # Edge-based style setters/getters
    def get_position(self, edge: Edge | int) -> YGValue: ...
    def set_position(self, edge: Edge | int, value: YGValue | float) -> None: ...
    def set_position_percent(self, edge: Edge | int, value: float) -> None: ...
    def set_position_auto(self, edge: Edge | int) -> None: ...
    def get_margin(self, edge: Edge | int) -> YGValue: ...
    def set_margin(self, edge: Edge | int, value: YGValue | float) -> None: ...
    def set_margin_percent(self, edge: Edge | int, value: float) -> None: ...
    def set_margin_auto(self, edge: Edge | int) -> None: ...
    def get_padding(self, edge: Edge | int) -> YGValue: ...
    def set_padding(self, edge: Edge | int, value: YGValue | float) -> None: ...
    def set_padding_percent(self, edge: Edge | int, value: float) -> None: ...
    def get_border(self, edge: Edge | int) -> float: ...
    def set_border(self, edge: Edge | int, value: float) -> None: ...
    def get_gap(self, gutter: Gutter | int) -> YGValue: ...
    def set_gap(self, gutter: Gutter | int, value: YGValue | float) -> None: ...
    def set_gap_percent(self, gutter: Gutter | int, value: float) -> None: ...

    # Dimension convenience setters
    def set_width_auto(self) -> None: ...
    def set_width_percent(self, value: float) -> None: ...
    def set_width_fit_content(self) -> None: ...
    def set_width_max_content(self) -> None: ...
    def set_width_stretch(self) -> None: ...
    def set_height_auto(self) -> None: ...
    def set_height_percent(self, value: float) -> None: ...
    def set_height_fit_content(self) -> None: ...
    def set_height_max_content(self) -> None: ...
    def set_height_stretch(self) -> None: ...
    def set_min_width_percent(self, value: float) -> None: ...
    def set_min_width_fit_content(self) -> None: ...
    def set_min_width_max_content(self) -> None: ...
    def set_min_width_stretch(self) -> None: ...
    def set_min_height_percent(self, value: float) -> None: ...
    def set_min_height_fit_content(self) -> None: ...
    def set_min_height_max_content(self) -> None: ...
    def set_min_height_stretch(self) -> None: ...
    def set_max_width_percent(self, value: float) -> None: ...
    def set_max_width_fit_content(self) -> None: ...
    def set_max_width_max_content(self) -> None: ...
    def set_max_width_stretch(self) -> None: ...
    def set_max_height_percent(self, value: float) -> None: ...
    def set_max_height_fit_content(self) -> None: ...
    def set_max_height_max_content(self) -> None: ...
    def set_max_height_stretch(self) -> None: ...
    def set_flex_basis_fit_content(self) -> None: ...
    def set_flex_basis_max_content(self) -> None: ...
    def set_flex_basis_stretch(self) -> None: ...

    # Layout results (read-only after calculate_layout)
    def calculate_layout(self, width: float, height: float, direction: Direction | int) -> None: ...
    @property
    def layout_left(self) -> float: ...
    @property
    def layout_top(self) -> float: ...
    @property
    def layout_right(self) -> float: ...
    @property
    def layout_bottom(self) -> float: ...
    @property
    def layout_width(self) -> float: ...
    @property
    def layout_height(self) -> float: ...
    @property
    def layout_direction(self) -> Direction: ...
    @property
    def layout_had_overflow(self) -> bool: ...
    @property
    def layout_raw_width(self) -> float: ...
    @property
    def layout_raw_height(self) -> float: ...
    def layout_margin(self, edge: Edge | int) -> float: ...
    def layout_padding(self, edge: Edge | int) -> float: ...
    def layout_border(self, edge: Edge | int) -> float: ...

# Batch layout helpers
def configure_node_fast(
    node: Node,
    *,
    width: float | str | None = None,
    height: float | str | None = None,
    min_width: float | str | None = None,
    min_height: float | str | None = None,
    max_width: float | str | None = None,
    max_height: float | str | None = None,
    flex_grow: float | None = None,
    flex_shrink: float | None = None,
    flex_basis: float | str | None = None,
    flex_direction: str | None = None,
    flex_wrap: str | None = None,
    justify_content: str | None = None,
    align_items: str | None = None,
    align_self: str | None = None,
    gap: float | None = None,
    overflow: str | None = None,
    position_type: str | None = None,
    padding_top: float = 0.0,
    padding_right: float = 0.0,
    padding_bottom: float = 0.0,
    padding_left: float = 0.0,
    margin: float | None = None,
    margin_top: float | None = None,
    margin_right: float | None = None,
    margin_bottom: float | None = None,
    margin_left: float | None = None,
    pos_top: float | str | None = None,
    pos_right: float | str | None = None,
    pos_bottom: float | str | None = None,
    pos_left: float | str | None = None,
) -> None: ...
def clear_node_cache(node: Node) -> None: ...
def apply_layout_tree(
    root: object, offsets: dict[str, int], origin_x: int = 0, origin_y: int = 0
) -> list[LayoutRepaintFact]: ...
def get_layout_batch(node: Node) -> tuple[int, int, int, int]: ...

# Event system
def event_subscribe(callback: Callable[[int, EventType, Any], None]) -> None: ...
def event_reset() -> None: ...
